version: "3.10"

services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fullstack-net

  server:
    build: ./server
    container_name: express-server
    env_file:
      - ./server/.env.production
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - mongodb
    networks:
      - fullstack-net

  client:
    build: ./client
    container_name: react-client
    ports:
      - "127.0.0.1:5174:3000"
    depends_on:
      - server
    networks:
      - fullstack-net

networks:
  fullstack-net:
    driver: bridge

volumes:
  mongo-data:
